---
layout: post
title: Generator
date: 2018-04-09
tags: [node]
---

在准备学习koa之前，需要了解一下async，在了解async之前就需要知道Generator。

Generator本质上是一个函数，它的特点就是可以被中断，然后恢复执行，通常来说，当开发者调用一个函数之后，这个函数就脱离了开发者的控制，只用函数执行完毕之后，控制权才真正回到调用者手中，因此程序员在编写方法代码时，唯一能够影响方法执行的只有预先定义return关键字。

Promise也是如此，我们也无法控制Promise执行，新建一个Promise后，其状态自动转换为pending。同时执行，直到状态改变后，我们才能执行下一步操作。

而Generator就不一样，它可以由用户执行终端或者恢复执行的操作，Generator中断后可以转去执行其它操作，然后再回头从中断的地方恢复执行。

### use Generator

Generator函数和普通函数最大区别

- function关键字和方法名中间有个星号"*";
- 函数体中使用yield关键字

    function * GeneratorExample() {
        yield "hello world";
        return "end";
    }

yield关键字用来定义函数的执行状态，如果一个Generator函数中定义了x个关键字，那么就有x+1个状态。（最后的return状态）

### Generator execute

当调用Generator函数之后，Generator对象会逐个经历所有状态，知道Generator函数执行完毕。该函数也不会立刻执行，函数的返回结果页不是字符串，而是一个对象，可以将它理解为一个指针，指向Generator函数当前的状态。

当Generator被调用后，指针指向方法体的第一行，当调用next方法后，指针指向第一个yield语句。以第一个函数为例：

    var gen = GeneratorExample();
    console.log(gen.next()); // {value: 'hello world', done: false}
    console.log(gen.next()); // {value: "end", done:true};
    console.log(gen.next()); // {value: 'end', done: true};

### yield关键字

yield 本意为“生产”，当next方法被调用的时候，Generator函数开始向下执行，当遇到yield关键字，会暂停操作，并且对yield后的表达式进行求职，无论yield返回的是任何类型的值，yield操作最后返回的都是一个对象，该对象有value和done两个属性。

那么要注意的是，yield关键字本身是不产生返回值。例如：

    function * foo (x) {
        let y = yield(x + 1);
        return y;
    }
    let gen = foo(5);
    console.log(gen.next()); // {value: 6, done: false};
    console.log(gen.next()); // {value: undefined, done: true}

第二个next方法执行之后，y的值为undefined，表明，y在yield(x+1)语句中没有成功赋值，而yield关键字本省就可以视为一个不产生返回值的函数，因此y并没有被赋值。如果要计算y的值，改成这样：   

    function * gen(x) {
        let y = 0;
        yield y = x + 1;
        return "end";
    }

next方法可以接受一个参数，表示yield求职的结果。

    function * foo (x) {
        let y = yield(x+1);
        return y;
    }
    let gen = foo(5);
    console.log(gen.next()); // {value: 6, done: false};
    console.log(gen.next(10)); // {value: 10, done: true};

    // is the same as 
    function * foo(x) {

        let y = yield(x+1);
        y = 10;
        return y;
    }
    let gen = foo(5);
    console.log(gen.next()); // {value: 6, done: false};
    console.log(gen.next()); // {value: 10, done: true};

### next 方法与Iterator接口

Generator函数返回的一个对象是具有Iterator，可以用遍历Iterator接口的方法来执行generator，for  of，array.from()等。

当我们使用for of 循环的方式来执行generator函数内的步骤，由于for/of本身就会调用next方法，因此不需要手动调用。

循环会在done属性为true的时候停止。

    function * Generator() {
        yield "hello Node";
        yield "From Lear";
        return "end" 
        // return yield "end";
    }
    var gen = Generator();
    for (let i of gen) {
        console.log(i);  // hello Node  , From Lear 不会打印出end，如果要打印出，使用代码注释中的表达
    }

### 错误处理

使用Generator函数的原型中定义了throw方法。

    function * Generator() {
        try {
            yield console.log('hello');
        } catch(e) {
            console.log(e);
        }
        yield console.log("node");
        return "end"
    }
    var gen = Generator();
    gen.next();
    gen.throw("throw error");
    // hello ... throw  error ... Node 

Generator的原型对象还定义了return()方法，用来结束一个Generator函数的执行，这和函数内部额的return不是一回事。

    funciton * Generator() {
        yield console.log("hello NOde");
        yield console.log("From Lear");
        return "end";
    }
    var gen = Generator();
    gen.next(); // "hello Node";
    gen.return ();
    // return 方法后面的next不会被执行
    gen.next()


